env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:svelte/recommended
overrides:
  [
    {
      files: ['*.svelte'],
      parser: 'svelte-eslint-parser',
      # Parse the `<script>` in `.svelte` as TypeScript by adding the following configuration.
      parserOptions: {
        parser: '@typescript-eslint/parser'
      }
    },
  ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions:
    - .svelte
plugins:
  - 'eslint-plugin-svelte'
rules: 
  'svelte/mustache-spacing':
    - error
    - tags:
        openingBrace: never
        closingBrace: never
