name: ESLint Linting

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

  svelte-remote:
    name: Lint Svelte remote app
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Linting
        run: eslint svelte-mf-app/remote/src
    
