name: Linting Single SPA MF

on:
  pull_request:
    branches:
      - main
    paths:
      - 'single-spa/**'

jobs:
  react-remote:
    name: Lint remote app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install eslint --global
      - name: Install dependencies
        working-directory: single-spa/counter
        run: npm install

      - name: Linting
        working-directory: single-spa/counter
        run: npm run lint

  react-host:
    name: Lint host app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install eslint --global
      - name: Install dependencies
        working-directory: single-spa/root-config
        run: npm install

      - name: Linting
        working-directory: single-spa/root-config
        run: npm run lint
