name: Linting Svelte MF with Softarc plugin

on:
  pull_request:
    branches:
      - main
    paths:
      - 'svelte-mf-app/softarc-plugin/**'

jobs:
  svelte-remote-softarc:
    name: Lint remote app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install eslint --global
      - name: Install dependencies
        working-directory: svelte-mf-app/softarc-plugin/remote
        run: npm install

      - name: Linting
        working-directory: svelte-mf-app/softarc-plugin/remote
        run: eslint src

  svelte-host-softarc:
    name: Lint host app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install eslint --global
      - name: Install dependencies
        working-directory: svelte-mf-app/softarc-plugin/host
        run: npm install

      - name: Linting
        working-directory: svelte-mf-app/softarc-plugin/host
        run: eslint src
